### PR TITLE
commenting out the default UIAlertView

### PR DESCRIPTION
**Pull request by aYoussef**

### CODE REVIEW

**Comment by oaosman84** [comment]
LGTM

**Comment by oaosman84** [comment]
Let's let Karim review this

**Comment by kfateem** [comment]
Need a little more context. Why are we commenting out the UIAlertView? 

What happens when a notification is received while the app is in the background?

**Comment by kfateem** [comment]
I guess the handling has moved to:
https://github.com/Parlio/PushPlugin/pull/1/files

LGTM. Can you please remove the commented out block then merge?

**Pull request merged**
